[tool.poetry]
name = "crew-assembler"
version = "0.1.0"
description = "..."
authors = ["hex benjamin <hex@hexbenjam.in>"]
license = "GPL-v3-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
crewai = "^0.5.5"
# requests = "^2.31.0"
# beautifulsoup4 = "^4.12.3"

[tool.poetry.group.dev.dependencies]
sourcery = "^1.15.0"

[tool.poetry.scripts]
assembler = "crew_assembler.assembler:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
