[tool.poetry]
name = "crew-assembler"
version = "0.2.0"
description = "..."
authors = ["hex benjamin <hex@hexbenjam.in>"]
license = "GPL-v3-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
crewai = "^0.10.0"
tomlkit = "^0.12.3"
click = "^8.1.7"

[tool.poetry.group.dev.dependencies]
sourcery = "^1.15.0"

[tool.poetry.scripts]
assembler = "crew_assembler.cli:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
