# CREW_ASSEMBLER CONFIGURATION FILE [TEMPLATE]
# all tools: ["_human", "_ddg_search", "html", "memory_write", "memory_read", "yt_transcript"]

[crew]
id = ""
name = ""
description = ""
process = "sequential" # "sequential" or "hierarchical" for now

model = "ollama/HEXB-MythoMax-L2-13B:latest"
# model = "openai/gpt-3.5-turbo"
# model = "hf/provider/model"

base_url = "http://connect.hexbenjam.in"

# > AGENTS <

[[agent]]
id = ""
role = ""
backstory = ""
goal = ""
delegation = false
verbose = true
tool_ids = ["_human"]

# > TASKS <

[[task]]
id = ""
agent_id = ""
description = ""
expected_output = ""
context = ""
tool_ids = ["_human"]
