[crew]
id = "yt_summarizer"
name = "YouTube Summarizer"
description = "Summarize a YouTube video as a Markdown note."
process = "sequential"                                        # "sequential" or "hierarchical" for now

model = "ollama/hexbenjamin/memgpt-dpo-uncensored:q8_0"
base_url = "http://connect.hexbenjam.in"

# > AGENTS <

[[agent]]
id = "yt_fetcher"
role = "YouTube Transcript Fetcher"
backstory = "You are an expert in retrieving transcripts from YouTube videos. Your task is to fetch the transcript for the provided YouTube link."
goal = "Fetch the transcript for the YouTube video using your provided tools."
delegation = false
verbose = true
tool_ids = ["yt_transcript"]

[[agent]]
id = "summarizer"
role = "Video Summarizer"
backstory = "You are an expert note-taker. You have a knack for summarizing videos and articles in a few paragraphs. You are tasked with summarizing a YouTube video's transcript."
goal = "Summarize the video's transcript concisely but completely."
delegation = false
verbose = true
tool_ids = []

[[agent]]
id = "editor"
role = "Markdown Editor"
backstory = "You are an expert in Markdown syntax."
goal = "Create a finalized Markdown note from input materials."
delegation = false
verbose = true
tool_ids = []

# > TASKS <

[[task]]
id = "summarize_video"
agent_id = "summarizer"
description = "Use your tools to retrieve the transcript for this YouTube video: {}. Then, summarize the video's transcript. Aim for the length of your output text to be about 1/3 of the input text's length."
expected_output = "A summary of the transcript of the provided YouTube video, focusing on accuracy and concise phrasing."
context = []
tool_ids = ["yt_transcript"]

[[task]]
id = "edit_markdown"
agent_id = "editor"
description = "Create a finalized Markdown note from the input materials. One is a video's transcript, and the other is a summary of that transcript."
expected_output = "A finalized Markdown note, free of errors, and utilizing any features of Markdown that help communicate the information more clearly."
context = ["summarize_video"]
tool_ids = []
